### PR TITLE
Fix two concurrency bugs in WebJobs MessageReceiver

### PR DESCRIPTION
**Pull request by dgchurchill**
MessageReceiver configures the bus on the fly when it receives the
first message. The configuration calls are made within a lambda passed
to a ConcurrentDictionary.GetOrAdd call. While this ensures that the
dictionary remains consistent if messages are handled on different
threads, it doesn't prevent the configuration code from being called
multiple times or from being called concurrently on different
threads. From the documentation from GetOrAdd: "If you call GetOrAdd
simultaneously on different threads, valueFactory may be called
multiple times, but only one key/value pair will be added to the
dictionary."

The underlying registration methods are not
threadsafe (e.g. MassTransit.Registration.Registration.ConfigureConsumers
adds an element to an ordinary HashSet without any locking).

This commit:
- changes the value type in the ConcurrentDictionary to be a Lazy<> to
ensure the configuration is only executed a single time
- adds a lock to ensure that concurrent calls to the Handle* methods
for different queues / topics don't call the registration methods concurrently.

### CODE REVIEW

**Review by perrymana — COMMENTED** [review]
I still don't understand why both the Lazy and the lock required? Shouldn't either one of them fix the problem?

Also should the _configureLock not be static to it handle locking across different MessageReceiver instances?

**Comment by perrymana** [comment]
> I still don't understand why both the Lazy and the lock required? Shouldn't either one of them fix the problem?
> 
> Also should the _configureLock not be static so it can handle locking across different MessageReceiver instances?

Oh! Lazy isn't going to work when calling GetOrAdd for different queueNames... ok. I suspect the _configureLock should still be static (and then the Lazy isn't truly necessarily)

**Comment by dgchurchill** [comment]
> Also should the _configureLock not be static so it can handle locking across different MessageReceiver instances?
@perrymana oh, that's a good point. I'm reluctant to make it static though because it feels a bit broad. The extension method in this library that configures MassTransit does register MessageReceiver as a singleton though so I think it's an unlikely use-case. What do you think?

> (and then the Lazy isn't truly necessarily)
I think the Lazy is also necessary to ensure that the configuration code isn't executed twice for the same queue. I took a quick look at some of the Configure* method bodies and it looks like some of them add things to lists so calling them twice doesn't seem to be expected.

I could put the lock on the *outside* of the `GetOrAdd` call but then I'd be affecting performance I think....

**Comment by perrymana** [comment]
I've always used static objects for locks, since you are usually trying to lock things across multiple threads/instances. The fact it is registered as a singleton kind of means it is irrelevant... but what if it wasn't a singleton?

Good point with the Lazy, I'm happy with that

**Comment by perrymana** [comment]
> I could put the lock on the outside of the GetOrAdd call but then I'd be affecting performance I think....

Oh yeah don't do that!

**Comment by dgchurchill** [comment]
> I've always used static objects for locks, since you are usually trying to lock things across multiple threads/instances. The fact it is registered as a singleton kind of means it is irrelevant... but what if it wasn't a singleton?

@perrymana maybe we have a quick chat about this this morning if you have a sec? I think MessageReceiver has to have a long lifetime otherwise all the concurrent dictionary stuff isn't much use. I guess you could have two long-lived MessageReceivers but I think if you did that it'd only be useful if they each had their own separate bus configs, in which case they wouldn't step on each other.

**Review by perrymana — APPROVED** [review]
I think this is fine. As you have said everything is a singleton so it ultimately doesn't matter. I'm happy if you want to leave it.

**Comment by dgchurchill** [comment]
Fix has been merged into parent repo

**Pull request closed without merging**
